import{a as v,S as E,i as a}from"./assets/vendor-Dy2ZTtfi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const S=15,m=async(s,o=1)=>(await v.get("https://pixabay.com/api/",{params:{key:"51410933-6e28737e6449aa5e8ee5fd880",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:S,page:o}})).data;let c;const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more"),g=s=>{const o=s.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",o),c?c.refresh():c=new E(".gallery a",{captionsData:"alt",captionDelay:250})},P=()=>{p.innerHTML=""},y=()=>{f.classList.remove("hidden")},b=()=>{f.classList.add("hidden")},R=()=>{h.classList.remove("hidden")},L=()=>{h.classList.add("hidden")},w={form:document.querySelector(".form"),button:document.querySelector(".load-more")};let i="",n=1;const q=15;let d=0;const M=async s=>{if(s.preventDefault(),L(),i=s.target.elements["search-text"].value.trim(),!i){a.warning({title:"Warning",message:"Search field cannot be empty.",position:"topRight"});return}P(),n=1,y();try{const o=await m(i,n),e=o.hits;if(d=Math.ceil(o.totalHits/q),e.length===0){a.info({title:"No results",message:"Sorry, no images match your search query.",position:"topRight"});return}g(e),d>1?R():a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(o){console.error(o),a.error({title:"Error",message:"Failed to load images. Please try again.",position:"topRight"})}finally{b()}},$=async()=>{n+=1,y();try{const o=(await m(i,n)).hits;g(o);const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2+16,behavior:"smooth"}),n>=d&&(L(),a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){console.error(s),a.error({title:"Error",message:"Failed to load images. Please try again.",position:"topRight"})}finally{b()}};w.form.addEventListener("submit",M);w.button.addEventListener("click",$);
//# sourceMappingURL=index.js.map
