import{a as E,S as $,i}from"./assets/vendor-Dy2ZTtfi.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function t(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(o){if(o.ep)return;o.ep=!0;const s=t(o);fetch(o.href,s)}})();const q=15,m=async(r,e=1)=>(await E.get("https://pixabay.com/api/",{params:{key:"51410933-6e28737e6449aa5e8ee5fd880",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:q,page:e}})).data;let u;const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),g=document.querySelector(".load-more"),b=r=>{const e=r.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t.likes}</p>
          <p><b>Views:</b> ${t.views}</p>
          <p><b>Comments:</b> ${t.comments}</p>
          <p><b>Downloads:</b> ${t.downloads}</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",e),u?u.refresh():u=new $(".gallery a",{captionsData:"alt",captionDelay:250})},P=()=>{h.innerHTML=""},w=()=>{y.classList.remove("hidden")},L=()=>{y.classList.add("hidden")},R=()=>{g.classList.remove("hidden")},v=()=>{g.classList.add("hidden")},M={form:document.querySelector(".form"),button:document.querySelector(".load-more")};let d="",c=1;const B=15;let f=0;const H=async r=>{if(r.preventDefault(),v(),d=r.target.elements["search-text"].value.trim(),!d){i.warning({title:"Warning",message:"Search field cannot be empty.",position:"topRight"});return}P(),c=1,w();try{const e=await m(d,c),t=e.hits;if(f=Math.ceil(e.totalHits/B),t.length===0){i.info({title:"No results",message:"Sorry, no images match your search query.",position:"topRight"});return}b(t),f>1?R():i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(e){console.error(e),i.error({title:"Error",message:"Failed to load images. Please try again.",position:"topRight"})}finally{L()}},I=async()=>{c+=1,w();try{const e=(await m(d,c)).hits;b(e);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2+16,behavior:"smooth"}),c>=f&&(v(),i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){console.error(r),i.error({title:"Error",message:"Failed to load images. Please try again.",position:"topRight"})}finally{L()}};M.form.addEventListener("submit",H);M.button.addEventListener("click",I);const O=document.querySelector('input[name="search-text"]'),n=document.querySelector('button[type="submit"]'),p=new Audio("./sounds/run.mp3");function W(){const r=window.innerWidth,e=window.innerHeight,t=Math.floor(Math.random()*(r-n.offsetWidth)),a=Math.floor(Math.random()*(e-n.offsetHeight));n.style.position="fixed",n.style.left=`${t}px`,n.style.top=`${a}px`}function T(r=6,e=5,t=40){let a=0;const o=parseInt(n.style.left,10)||n.offsetLeft,s=parseInt(n.style.top,10)||n.offsetTop,l=setInterval(()=>{const S=(Math.random()-.5)*e*2,x=(Math.random()-.5)*e*2;n.style.left=`${o+S}px`,n.style.top=`${s+x}px`,a++,a>=r&&(clearInterval(l),n.style.left=`${o}px`,n.style.top=`${s}px`)},t)}n.addEventListener("mouseenter",()=>{O.value.trim()||(W(),T(),p.currentTime=0,p.play())});
//# sourceMappingURL=index.js.map
